name: Test

on:
  workflow_call:

# Set permissions at the job level.
permissions: {}

env:
  PYTHONUNBUFFERED: 1
  FORCE_COLOR: 1

jobs:
  test:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ['3.13']
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
    - name: Install pre-requisites (e.g. hatch)
      run: python -m pip install --require-hashes --requirement=requirements/ci
    - name: Run test suite
      run: hatch run cov
      env:
        TERM: dumb # keep rich from printing escape sequences, which made testing CLI outputs messy
